### PR TITLE
Red Bull spelling and image replacement

### PR DESCRIPTION
**Pull request by ttscoff**
- RedBull -> Red Bull
- New car image

### CODE REVIEW

**Comment by ttscoff** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by timclegg** [comment]
@ttscoff The replacement image is 2.11MB in size.  Since this is used in the `README` by anyone who will open the page, is it possible to resize it to be smaller in size... maybe <=300KB?  We really don't need (or want) a high-res image that's potentially slow in loading (particularly in lower bandwidth conditions).

**Comment by ttscoff** [comment]
> @ttscoff The replacement image is 2.11MB in size. 

Dropped to 92k.

**Review by timclegg — APPROVED** [review]
Great job!  Thank you

**Pull request merged**
